nelmio_api_doc:
    documentation:
        info:
            title: Product API
            description: API for managing products
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$) 